### ISSUE TITLE
BPM text size - UI enhancement

### ISSUE THREAD

**Issue by twentyfortysix** [teragonaudio/BeatCounter#17]
Hello, thanks for the perfect plugin!

Let me add one suggestion.
As the main goal of this plugin is to get the current BPM I would suggest to increase the numbers and decrease the size of the buttons as they are not that visually important.
My scenario is that I play (live) or work bit further from the screen and all I see are the buttons ;) but I want to see the numbers indeed ;)

like so:
![ui-beatcounter](https://cloud.githubusercontent.com/assets/747153/4107446/e379118a-31c7-11e4-88cd-0af0bdecae0a.png)
(I'm not saying it should be like that, but conceptually..)

**Comment by nikreiman** [comment]
Sorry it took so long to implement this; I don't have much time for plugin programming these days. Anyways, this fix has been pushed to `master` and will go out in the next version. Here's a screenshot of the new UI in action:

![screen shot 2015-04-18 at 20 26 15](https://cloud.githubusercontent.com/assets/312573/7216747/c1f6dfa0-e609-11e4-8539-fecea524f630.png)

**Comment by twentyfortysix** [comment]
cool :)
